package Util;

public class UtilYoutube {
    public static String[] movieName = {
            "Thuldai",
            "Muna Madan",
            "Highway to Dhampus",
            "Saas Fere Jasto Lagcha",
            "Chhakka Panja",
            "Yug Dekhi Yug Samma",
            "Kohi Mero",
            "Visa Girl",
            "I Am Sorry",
            "Darpan Chhaya",
            "Batch No.16",
            "Resham Filili",
            "Aago",
            "White Sun",
            "Lukamari",
            "Home",
            "Saayad 2",
            "Chandra",
            "Maya",
            "Nepal's Stolen Children",
            "Fanko",
            "Acharya",
            "Chankhe Shankhe Pankhe",
            "Chaukaith",
            "Pooja",
            "Raghav",
            "God Lives in the Himalayas",
            "Ozone Layer",
            "Masaan",
            "Jerryy",
            "Mission Paisa",
            "KTM Cocktale",
            "Punam",
            "The Rickshaw Puller",
            "Hostel Returns",
            "Kumari",
            "Kabaddi",
            "Super Star",
            "Birami Sahar (Sick City)",
            "Pralobhan",
            "Mero Euta Saathi Cha",
            "Manakamana",
            "Ajhai Pani",
            "Sunakali",
            "Ritu",
            "Fever",
            "Fitkiree",
            "Auntie Ganga",
            "Loot 2",
            "Badal Paree",
            "Suntali",
            "Journey of a Red Fridge",
            "First Love",
            "Apabad",
            "Love in Nepal",
            "Living Goddess",
            "Love You Baba",
            "Ko Afno",
            "Nata Ragat Ko",
            "Jetho Kancha",
            "Sherpa",
            "Anaagat",
            "Kusume Rumal",
            "Lama La",
            "The Black Hen",
            "Gaunthali",
            "Chino",
            "Sahasi Chori",
            "Red Monsoon",
            "Seto Bagh",
            "Saanghuro",
            "Sands of Silence",
            "Happy New Year",
            "The Necklace",
            "November Rain",
            "Choose Your Own Adventure: The Abominable Snowman",
            "The Winner",
            "Kabaddi Kabaddi",
            "Nabarsiyeki Jhari",
            "Palash",
            "Siudo Ko Sindoor",
            "Maya Namara",
            "Aama",
            "Dying Candle",
            "Parivara",
            "Small World",
            "Ritu",
            "Loot",
            "Kagbeni",
            "Chha Ekan Chha",
            "Gajalu",
            "Zhigrana",
            "Chhadke",
            "Janma Bhoomi",
            "Death Zone: Cleaning Mount Everest",
            "Nepal, in the Mountain's Shadow",
            "Basain",
            "Ma Byujiyepachi",
            "Numafung",
            "Swor-The Melody of Dreams",
            "Dreams",
            "Deciphering Me",
            "Uma",
            "Drawing the Tiger",
            "I Am Happy",
            "Mokshya",
            "Je Bho Ramrai Bho",
            "Himalaya",
            "Soongava: Dance of the Orchids",
            "Prem Pinda",
            "Mukundo",
            "Kusume Rumal",
            "Jatra",
            "Facing the Giant Bees",
            "Ber Pipal",
            "Jhola",
            "Samaya Ra Paristhiti",
            "Untouchable: Children of God",
            "Kabaddi Kabaddi",
            "Nostalgia Musical",
            "Kagbeni",
            "Teen Ghumti",
            "Nepal Pyaro Chha",
            "Dakshina",
            "BabuSaheb",
            "Daag",
            "Kafal pakyo",
            "Gothalo",
            "Mero Love Story",
            "Talakjung vs Tulke",
            "Highway",
            "Kusume Rumal 2",
            "Saanghuro",
            "Hostel",
            "Woman Rebel",
            "Shankar",
            "Paral Ko Aago",
            "Kathmandu",
            "Children of God",
            "DristiBhram",
            "Safar",
            "Bansulli",
            "Kleine Wölfe",
            "Basanti",
            "Pashupati Prasad",
            "Namaste Nepal"
    };

    public static String[] movieTitle = {
            " Thuldai Thuldai Ye Thule || Udit Narayan Jha || Deepa Narayan Jha || Nepali Old Movie Thuldai Song",
            " MUNA MADAN  || New Release || Premiere @ Budhasubba Digital",
            " Highway to Dhampus - Official Trailer",
            " Saas Fere Jasto Lagcha - Exclusive Trailer (HD)",
            " CHHAKKA PANJA - New Nepali Movie Official Trailer 2016 Ft. Deepak Raj Giri, Priyanka Karki",
            " Tin Pate Danda Katera | Yug Dekhi Yug Samma | Rajesh Hamal | Krishti Mainali",
            " Kohi Mero Official Theatrical Trailer .lexlimbu",
            " VISA GIRL - Official Theatrical Trailer",
            " I am Sorry- Official Trailer",
            " Darpan Chhaya - Superhit Nepali Movie || Niruta Singh, Dilip Rayamajhi, Uttam Pradhan, Jitu Nepal",
            " Nepali film trailer Batch No.16",
            " Resham Filili || रेशम फिलिली || Official Trailer",
            " Maya Basyo Mutuma || Nepali Movie AAGO Song || Sushil Chhetri, Saranga Shrestha || Komal, Yam Baral",
            " WHITE SUN - New Nepali Movie Official Trailer 2016 Ft.  Dayahang Rai, Rabindra Singh Baniya",
            " New Nepali Movie Trailer \"LUKAMARI\"  || Saugat Malla,Karma,Surbina Karki || Official Trailer",
            " GHAR | Nepali Horror Movie Official Trailer-2019/2076 |  Arpan Thapa,Surakshya Panta,Benisha Hamal",
            " SAAYAD 2 - New Nepali Movie Official Trailer 2017 Ft. Sushil Shrestha, Sharon Shrestha",
            "Sorry not available",
            "Sorry not available",
            " Nepal's Stolen Children | A Maiti Nepal Documentary with CNN. #maitinepal  #CNNFreedomProject",
            " FANKO || फन्को || Nepali Movie || Official Trailer",
            " Acharya trailer",
            " Trailer Launch- Nepali Movie \"Chankhe Shankhe Pankhe\" || \"चँखे शँखे पँखे\"",
            "Sorry not available",
            "Sorry not available",
            " RAGHAV - Official Theatrical Trailer (HD)",
            " God Lives in the Himalayas - Official Trailer",
            " Youtube Shorts Fix This Video Is Not Available Problem Solved",
            " Happiness In Second Marraige | Nepali Movie MASHAN | Ft. Raj Ballav Koirala, Keki Adhikari",
            " JERRY Nepali Movie Trailer 2014",
            " Dhala Dhala | Mission Paisa | Melina Manandhar | Alok Nemwang | Rajan Ishan | Rajesh Payal Rai",
            " FULL FILM NOW ONLINE!!!| OFFICIAL TEASER| KTM COCK-TALE",
            "Sorry not available",
            "Sorry not available",
            " Hostel Returns || Official Trailer || Nepali Movie || Full HD",
            " Nepali Old Movie Kumari / नेपाली पहिलो रंगीन चलचित्र कुमारी / KUMARI",
            " Kabaddi - Official Trailer - Dayahang & Nischal | Directed by Ram Babu Gurung",
            " Mayaluko Maya Mitho - Nepali Movie SUPER STAR Song || Bhuwan K.C., Sumi Khadka || Udit, Sadhana",
            " SICK CITY | New Nepali Movie Teaser 2017/2074 | Murray Kerr | Arpan Thapa, Sara Lama",
            " Nepali Movie PRALOVAN Teaser",
            " K Yo Maya Ho | Nepali Movie Song | Mero Euta Saathi Chha | Aaryan Sigdel | Namrata Shrestha",
            " Sapana Ko Bato | Nepali Film Manakamana | Karishama | Shiva | AB Pictures Farm | BG Dali",
            " AJHAI PANI | Nepali Movie Official Trailer | Puja Sharma | Alok Nembang | Sudarshan Thapa",
            "Sunakali: International Award Winning Documentary",
            "Sorry not available",
            " Nepali Movie FITKIREE | Official Theatrical Trailer | Saugat Malla | Diya Maskey | Nischal Basnet",
            "Sorry not available",
            "Sorry not available",
            " LOOT 2 - New Nepali Movie Official Trailer 2017/2073 Ft. Saugat Malla, Dayahang Rai",
            " Yo Jindagile K Garyo K Garyo || Sonu Nigam || Badalpari Movie Song ||",
            " SUNTALI Official Trailer 2.0 (Nepali)",
            " IDFA 2007 | Trailer | Journey of a Red Fridge",
            " Nepali Movie \"First Love\" Trailer - www.entertainnepal.com",
            " Apabad - Official Trailer",
            " Love In Nepal TRAILER - Jharana Bajracharya .lexlimbu",
            " Living Goddess - Trailer",
            " New trailer of Nepali movie \"Love you Baba\" - Directed by Saugat Bista(8 year boy)",
            " KO AFNO / OFFICIAL TEASER / Nepali Movie",
            " BEST OF नाता रगतको हेर्दा हेर्दै आँशु झरेको थाहै भएन -OLD IS GOLD - NEPALI MOVIE - Shree Krishna",
            " Rana Jyu | Jetho Kanchho | RAJESH HAMAL | JAL SHAH | REKHA THAPA | SHIVA SHRESTHA",
            " Sherpa Official Trailer 1 (2015) - Documentary HD",
            " ANAAGAT - New Nepali Movie Teaser || Arpan Thapa, Priyanka Karki, Praween, Rosin",
            " Kusume Rumal Trailer",
            " LAMA LA | New Nepali Movie Official Trailer",
            " The Black Hen Trailer | SGIFF 2015",
            "Sorry not available",
            " Mohani Lagla Hai | Nepali Movie Chino Song | Narayan Gopal, Asha Bhosle | Shiva Shrestha, Bhuwan KC",
            " TSAFF2017 - Sahasi Chori (brave girl) trailer",
            " Red Monsoon Official Trailer HD",
            " SETO BAGH || Nepali Movie Official Trailer || Nir Shah | Raja Ram Paudel | Shyam Rai",
            " Nepali Movie Sanghuro | Trailer",
            "Sorry not available",
            " HAPPY NEW YEAR | New Nepali Movie Teaser 2017 Ft. Kushal Thapa, Sandhay KC, Pukar Gautam",
            " Nepali Movie Trailer \"The Necklace\" (C-MALA) || RBA FILMS",
            " Superhit Nepali Movie || NOVEMBER RAIN || Aaryan Sigdel, Namrata Shrestha, Chhulthim Gurung",
            "Sorry not available",
            " THE WINNER Nepali Movie Official Trailer 2016 Ft. Malina Joshi, Mahesh Shrestha, Manchin Shakya 4K",
            " Kabaddi Kabaddi Nepali Movie Official Trailer / Teaser 2072",
            "Sorry not available",
            " New Nepali Movie PALASH Trailer 2017/2073 Ft. Rekha Thapa, Aayub KC, Kameshwor Chaurasiya",
            " Joban Phulyo Dali Dali Ma | Nepali Movie Song | Nepali Movie Siudo Ko Sindor | Niruta Singh",
            " Ke Soche The Jindagima Ke ke Bhayo aaja",
            " Old Nepali Full Classic Movie, AAMA आमा 1964 A D  ||  Nepal's First Movie 1964 A D",
            "Sorry not available",
            "Sorry not available",
            " Sano Sansar | Official Trailer | New Nepali Movie 2024",
            " New Nepali  Movie RITU - TRAILER on HD",
            " Loot (Nepali Film) - Official Theatrical Trailer",
            " Nepali Movie Trailor - KagBeni",
            " CHHA EKAN CHHA | Nepali Movie Official Teaser 2016 | Sandip Chhetri, Nita Dhungana, Deepak Raj Giri",
            "\"Gajalu\" Trailer Nepali Movie || Anmol K.C, Shristi Shrestha || Latest Movie 2016 Offcial Trailer",
            " NEW NEPALI FILM [ \"ZHIGRANA\" ] - FIRST OFFICIAL TRAILER",
            " CHHADKE-NEPALI FEATURE FILM OFFICIAL THEATRICAL TRAILER  HD",
            " JANMA BHUMI \"जन्मभूमि\" | Latest Nepali Movie Trailer 2016 | In Cinemas Chaitra 19/1st April",
            "DEATH ZONE: Cleaning Mount Everest (Official Trailer)",
            " Nepal, in the Mountains Shadow Documentary",
            " BASAIN film promo | बसाई फिल्म  Trailer | Awarded Movie | Lil Bahadur Chhetri | Subash Gajurel",
            "Sorry not available",
            " Jiu Dhanai ।जिउधनै ।- Pabitra Subba | Numafhung | Limbu Movie Song | Nepali Song",
            " SWOR OFFICIAL PROMO 2",
            " DREAMS Nepali Movie Official Trailer Ft. Anmol K.C, Samragyee Rajya Laxmi Shah, Bhuwan K.C 2016 4K",
            " New Nepali Movie Official Trailer - \"Taandro\" || Dayahang Rai || Latest Nepali Movie 2017",
            " UMA - OFFICIAL TRAILER  | Nepali Feature Film | Reeccha Sharrma, Saugat Malla, Mithila Sharma,",
            " DRAWING THE TIGER | Women Make Movies | Trailer",
            " I AM HAPPY || Nepali Short Film from Sikkim",
            " Mokshya | Theatrical Trailer | New Nepali Movie |",
            " Je Bho Ramrai Bho | Hari Bansha Acharya,Madan Krishna,Rajesh Hamal,Jal Shah | Nepali Movie Scene",
            " Himalaya (1999) | HD Trailer",
            " Nepali Movie SOONGAVA Trailer Ft. Saugat Malla, Nisha Adhikari, Deeya Maskey | Oscar Award Nominated",
            " Gairi Khet Ko || आशा भोस्लेको स्वरमा सदाबहार नेपाली गीत || Nepali Movie Prem Pinda ||",
            " Mukundo - Official Trailer | Gauri Malla, Mithila Sharma, Ratan Subedi | Jan 29",
            " भाग्य भए भेटौला टिकामा अर्को साल - Nepali Movie Kusume Rumal Song || Tripti Nadkar || Deepa Jha",
            " JATRA | New Nepali Movie Official Trailer | Bipin Karki, Rabindra S. Baniya, Barsha Raut",
            " Facing the giant bees | SLICE I Full documentary",
            " Janam Janam Jiula Sangai || Shree Krishna Shrestha, Pooja Chand || BAR PIPAL Nepali Movie Song",
            " Nepali Movie \"Jhola\" Trailer",
            " Samaya Ra Paristhiti - Short Movie",
            "Sorry not available",
            " Kabaddi Kabaddi Nepali Movie Official Trailer 2072",
            "Sorry not available",
            " Nepali Movie Trailor - KagBeni",
            " Nepali Movie -\"TIN GHUMTI\" Official Trailer - 2 || Based on B P Koirala's Novel || Latest movie 2016",
            " NEPAL PYARO CHHA",
            " Sapana bhai aakhama | Nepali Movie Song | Dakshana Movie | Ft . Bhuwan KC, Niruta Singh |",
            " TIMI KINA AAYO DHARTIMA | BABU SAHEB | NEPALI MOVIE SONG | BHUWAN KC |KARISHMA MANADHAR |SUSHMITA KC",
            " Cham Cham Chamkeka - DAAG (Nametiyeko Ghau) || Nepali Movie Song || Nikhil Upreti, Sanchita Luitel",
            " KAFAL PAKYO || काफल  पाक्यो ||  NEPALI FILM || OFFICIAL TRAILER",
            " Gothalo गोठालो Nepali Movie clip",
            " Udi Chhuna Chandralai | Mero Love Story Movie Song | Aaryan Sigdel | Vinay Shrestha | Reecha Sharma",
            " Talakjung vs Tulke | Trailer",
            " Highway New Nepali Film Trailer",
            " Kusume Rumal | Nepali Movie Song | Kusume Rumal 2",
            " New Nepali Movie Sanghuro HD trailer",
            " HOSTEL Nepali Movie Official Theatrical Trailer   HD",
            " Woman Rebel - New Day Films - Human Rights - Women's Studies",
            " Khulyo Khulyo Bato Khulyo | Nepali Movie Shankar Song | Rajesh Hamal | Bipana Thapa | Jal Shah",
            " Paral Ko Aago | Nepali Old Full Movie | Basundhara Bhusha | Tanka Sharma | Menuka Pradhan",
            " The trailer of Katmandu HQ, Nepal - A mirror in the sky - Iciar Bollain & Veronica Echegui - ENGLISH",
            " Children of God - Official Trailer",
            "Sorry not available",
            " Safar - A Journey | Nepali Movie Trailer | Manan Sapkota | Shibir Pokharel | Nurja Shrestha",
            " Bansulli - Exclusive Trailer (HD)",
            " Kleine Wölfe - Straßenkinder von Kathmandu Nepal",
            " Meri Basanti Pyaari Basanti | Basanti Nepali Movie Song | Rajesh Hamal |Karishma Manandhar |Nir Shah",
            " PASHUPATI PRASAD | Nepali Movie Official Trailer | Khagendra Lamichhane, Barsha Siwakoti",
            " Official trailer of Namaste Nepal releaseda"
    };

    public static String[] movieVideoId = {
            "ohODUkYW1Ho",
            "eocbEuJ6Hik",
            "ftzZPRsm3ZA",
            "nikH7tw5GxA",
            "msDN-Y0HIME",
            "_DRhSmL_cBo",
            "EksF_M0VXfc",
            "aBBLabl-NFM",
            "58Wwe58MVao",
            "SQG-vIuCe_4",
            "mMHWWwSYEpM",
            "ET-Ej6ic128",
            "XrNq50g3HJU",
            "ADtFVw-AdS0",
            "vE2uVWme43k",
            "xyi7YmTcgiI",
            "AkJGJuF9FzQ",
            "EPEq3gx377o",
            "EPEq3gx377o",
            "7BkZrIOzSMI",
            "KFVpTGWTudg",
            "yfrKyuW3AiM",
            "rBJ0zmJEbi0",
            "EPEq3gx377o",
            "EPEq3gx377o",
            "G7Cw0A8DRnk",
            "2TxS78yPnJQ",
            "UM96qGFy-R4",
            "x_RO3Km4vyI",
            "nISxeJnG9qw",
            "DTOiqLpn-Vs",
            "Yu5han83DHg",
            "EPEq3gx377o",
            "EPEq3gx377o",
            "S3GIWlRYyjM",
            "lnKUDMrJzpA",
            "QPsblfsA_0w",
            "nC6PeE7unxg",
            "ggxLXSNV8I4",
            "l3Ck0lRDkQQ",
            "58t791uy3So",
            "3D5Uk6ivdOs",
            "3Sb0FN6ecm0",
            "yXW_B02TpMg",
            "EPEq3gx377o",
            "ObRQoRCp95g",
            "EPEq3gx377o",
            "EPEq3gx377o",
            "nX2fcXN_Yks",
            "L5VduWdo48I",
            "L69F8LWkIK4",
            "uNrK1JpXeTo",
            "j6-bnYYP8LE",
            "V7RLOq2RIu0",
            "_KVEfbUILh8",
            "1eNtTYbAp0w",
            "_lLX_4aIdRg",
            "c0WGA4_c6TA",
            "YRGkS3fGP5Q",
            "f2uoszg90As",
            "hLSWVsV3-9g",
            "Fi3wD-aqCbc",
            "4MLY5bLkMCU",
            "K4nbSXh95OI",
            "8qOtWZFK7a8",
            "EPEq3gx377o",
            "pzcBs8XrvyQ",
            "pjatetlyHVk",
            "bOOMyvP0KSY",
            "wv5CElPlbdA",
            "cnl4JVH_J8E",
            "EPEq3gx377o",
            "2dAj4i1AMzA",
            "KElhKESRVnA",
            "CHvIJ9U1CBc",
            "EPEq3gx377o",
            "rcate6wPlGg",
            "lrB8ojw0ah4",
            "EPEq3gx377o",
            "WHznAzpnlyA",
            "zQ-Xf-ZbKa0",
            "dw5NDy4OqEI",
            "K9F0ozvcEWM",
            "EPEq3gx377o",
            "EPEq3gx377o",
            "rBLusRiXMRA",
            "zKsMNDGqvrE",
            "QfzRxXI2c7w",
            "szQcnPkTjj8",
            "tBM2mP04S9c",
            "hPVoGcI43yI",
            "T_ioehoUVF4",
            "YohNHMGvmA8",
            "aIKhM2Lmy30",
            "BI2TlvNJxCo",
            "31nNzIsAGUs",
            "xbMj7IRCISE",
            "EPEq3gx377o",
            "kEZ1NHcYEHQ",
            "JRfEzxlMoAk",
            "GIh38wkkPZY",
            "YI8MV8zD8g8",
            "oIX3r58USj0",
            "4n_gxBs2FyQ",
            "zeC6LCMb7Z0",
            "9s_rwkuhh0U",
            "ltZCIldnhzI",
            "vN--9D7rmlQ",
            "u9lmBO2Sn2I",
            "t2F0eWTw9PA",
            "Eh1p9dzzwp4",
            "cyjCegqc3KE",
            "c5YQejT_ybk",
            "kTy5q67gwIU",
            "eRzeDdi19Ic",
            "F6eK6iPazRg",
            "YodPvF_Ckm4",
            "EPEq3gx377o",
            "_aqNQY5zfZQ",
            "EPEq3gx377o",
            "yxvn3sQ1VUI",
            "Q5cF0lz9GEk",
            "gyNDUlubnzA",
            "W1nb5DHHlPw",
            "I6cZqvMzfi8",
            "CnKEyepGrUE",
            "as8OLP00fag",
            "YnkujXAtcoQ",
            "qmiulZjjVZM",
            "EweSy8ND6Us",
            "me3TUgCeh1I",
            "ZH0u7J8Vev4",
            "DFMoRbP1eTY",
            "uZotbTJqUg0",
            "-kRz4hms_P0",
            "0UpikFvYyq8",
            "Gzyl5_MYOyc",
            "ktxLyOTAkOQ",
            "oqKGoZZn5Yo",
            "EPEq3gx377o",
            "R3HBn37Iq-g",
            "SyEx6Ph7La8",
            "b6MhwP9wvFc",
            "m--v6hApSLI",
            "O3GRxW9IkTg",
            "hv5C93U7DXI"
    };

    public static String embedUrl(String videoId, String videoTitle){
        String url = "<iframe width=\"100%\" height=\"100%\" src=\"https://www.youtube.com/embed/"+videoId+"?autoplay=1\" title="+videoTitle+",\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" allowfullscreen></iframe>\n";
        return url;
    }

    public static int[] ids = {
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            30,
            31,
            32,
            33,
            34,
            35,
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44,
            45,
            46,
            47,
            48,
            49,
            50,
            51,
            52,
            53,
            54,
            55,
            56,
            57,
            58,
            59,
            60,
            61,
            62,
            63,
            64,
            65,
            66,
            67,
            68,
            69,
            70,
            71,
            72,
            73,
            74,
            75,
            76,
            77,
            78,
            79,
            80,
            81,
            82,
            83,
            84,
            85,
            86,
            87,
            88,
            89,
            90,
            91,
            92,
            93,
            94,
            95,
            96,
            97,
            98,
            99,
            100,
            101,
            102,
            103,
            104,
            105,
            106,
            107,
            108,
            109,
            110,
            111,
            112,
            113,
            114,
            115,
            116,
            117,
            118,
            119,
            120,
            121,
            122,
            123,
            124,
            125,
            126,
            127,
            128,
            129,
            130,
            131,
            132,
            133,
            134,
            135,
            136,
            137,
            138,
            139,
            140,
            141,
            142,
            143,
            144,
            145,
            146
    };
}
